stage 'Load a file from GitHub'
def jenkinsFile = fileLoader.fromGit("Prod-Pipeline/pipeline_scripts/Jenkinsfile.groovy", "https://github.com/ManasaB-N1/ECSCICDREPO.git", "main", "3f54d5cc-13eb-4bf1-b3cf-dee02a942a81", '')

stage 'Run method from the loaded file'
    
jenkinsFile
