stage 'Load a file from GitHub'
def jenkinsFile = fileLoader.fromGit("Uat-Pipeline/pipeline_scripts/Jenkinsfile.groovy", "https://github.com/ManasaB-N1/ECSCICDREPO.git", "main", "8a28dca5-0aef-47a8-b62b-f40a071d2715", '')

stage 'Run method from the loaded file'
    
jenkinsFile
